name: MSBuild

on: [push]

jobs:
  run-msbuild-vstest:
    runs-on: windows-latest
    name: Run MSBuild and VSTest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      id: checkout_code
    
    - name: Init and update submodules
      id: update_submodules
      run: |
        git submodule init
        git submodule update
      
    - name: Add cmake to PATH
      id: setup_cmake
      uses: jwlawson/actions-setup-cmake@v1.12
      with:
        cmake-version: latest
        
    - name: Generate VS Project
      id: generate_vsproject
      run: cmake -S vendor\glfw -B vendor\glfw\build

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
      id: setup_msbuild

    - name: Build
      id: build
      working-directory: Blazer3dviewport
      run: msbuild .\Blazer3dviewport.sln
     
    - name: Setup VSTest path
      uses: darenm/Setup-VSTest@v1
      id: setup_vstest
      
    - name: Run VSTest
      id: run_vstest
      working-directory: $\x64\debug\
      run: vstest.console.exe /Platform:x64 .\UnitTests1.dll
