name: MSBuild

on: [push]

jobs:
  run-msbuild-vstest:
    runs-on: windows-latest
    name: Run MSBuild and VSTest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      id: checkout_code

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
      id: setup_msbuild

    - name: Build
      id: build
      working-directory: $\blazer3d\Blazer3dviewport
      run: msbuild .\Blazer3dviewport.sln
     
    - name: Setup VSTest path
      uses: darenm/Setup-VSTest@v1
      id: setup_vstest
      
    - name: Run VSTest
      id: run_vstest
      working-directory: $\x64\debug\
      run: vstest.console.exe /Platform:x64 .\UnitTests1.dll
